# Exercícios NumPy  

Agora que aprendemos sobre NumPy, vamos testar seu conhecimento. Começaremos com algumas tarefas simples, para depois entrarmos nas perguntas mais complicadas.

#### Importe NumPy como np

In [ ]:
import numpy as np

#### Crie uma matriz de 10 zeros

In [ ]:
np.zeros(10)

#### Crie uma matriz de 10 ones

In [ ]:
np.ones(10)

#### Crie uma matriz de 10 cincos

In [ ]:
np.array([5]*10)

#### Crie um array de inteiros de 10 até 50

In [ ]:
np.arange(10,51)

#### Crie um array dos numeros pares de 10 até 50

In [ ]:
np.linspace(10,50,21)

#### Criei uma matriz 3x3 com valores variando de 0 até 8

In [ ]:
(np.random.rand(9)*8).reshape(3,3)

In [ ]:
np.random.randint(0,8,9).reshape(3,3)

In [ ]:
np.random.choice(range(9), 9,replace=False).reshape(3,3)

#### Crie uma matriz identidade 3x3

In [ ]:
np.eye(3,3)

#### Use NumPy para gerar números aleatórios entre 0 e 1

In [ ]:
np.random.rand(1)

#### Use Numpy para gerar um array de 25 números aleatórios tirados de uma distribuição normal.

In [ ]:
np.random.randn(25)

#### Crie a seguinte matriz:

In [ ]:
np.linspace(0.01,1,100)

#### Crie um array de tamanho 20 igualmente espaçado entre 0 e 1.

In [ ]:
np.linspace(0,1,20)

## Indexação Numpy e Seleção

Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [119]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [120]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [121]:
mat[3,4]


20

In [122]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [123]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [124]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Agora faça o seguinte

#### Obter a soma de todos os valores no "mat"

In [ ]:
mat.sum()

#### Obter o desvio padrão dos valores em mat

In [116]:
mat.std()

7.211102550927978


#### Obter a soma de todas as colunas em mat


In [117]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])