In [1]:
import numpy as np

In [2]:
l = [1,2,3]

In [3]:
np.array(l)

array([1, 2, 3])

In [4]:
l2 = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(l2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(3,16,4)

array([ 3.        ,  7.33333333, 11.66666667, 16.        ])

In [27]:
np.random.rand(6,3,2)

array([[[0.74788215, 0.85144639],
        [0.36839471, 0.27716751],
        [0.89651098, 0.92528059]],

       [[0.78061777, 0.10503159],
        [0.37383419, 0.07492051],
        [0.22883336, 0.20128148]],

       [[0.12500965, 0.85525856],
        [0.28049034, 0.54471498],
        [0.77126522, 0.27735553]],

       [[0.84003874, 0.21012846],
        [0.99388807, 0.45369088],
        [0.97304472, 0.58813435]],

       [[0.82763692, 0.41413489],
        [0.62862807, 0.60803686],
        [0.81152741, 0.61318445]],

       [[0.27918408, 0.54659396],
        [0.19079948, 0.83927079],
        [0.88712025, 0.23170446]]])

In [29]:
np.random.randn(5,4,3)

array([[[ 1.04970381,  0.24448765,  0.51661574],
        [ 1.13043054, -0.88021932, -1.14908412],
        [-0.9731363 ,  0.85349563, -0.48564904],
        [-0.08902133,  1.72192301,  1.03265455]],

       [[-1.18215073,  0.67015941,  1.33828315],
        [ 0.21897873, -1.35398399,  0.64266151],
        [ 0.71683384,  0.88109008,  1.15220465],
        [-0.23995408, -0.19706928, -0.07140796]],

       [[ 1.45861024, -1.14091841, -0.86560477],
        [-2.3382348 ,  0.177985  ,  1.50993004],
        [-1.93863776,  1.47213788,  1.93146361],
        [-0.73420304, -2.49744267,  1.09143371]],

       [[-1.10161606, -1.80276058, -0.64241063],
        [-0.75794392, -0.09266196, -0.23363101],
        [-0.48866981, -1.0655669 , -0.01521303],
        [ 0.99341728, -1.42041057, -0.87334576]],

       [[-0.08156155, -1.03147147,  0.69608413],
        [-1.54771498,  0.30734416, -0.77651801],
        [ 0.05120676, -1.11296245,  0.75503353],
        [-1.13256871, -1.46793698,  0.81740742]]])

In [30]:
np.random.randint(0,100,10)

array([13, 85, 50, 43, 76, 89, 93, 93, 21, 43])

In [31]:
arr = np.random.rand(25)

In [32]:
arr

array([0.14008585, 0.62940221, 0.87672557, 0.41558192, 0.72639928,
       0.1562309 , 0.69062982, 0.12441599, 0.71362922, 0.33172497,
       0.46539404, 0.71359483, 0.66458543, 0.20541592, 0.07947435,
       0.52723854, 0.17489917, 0.71518701, 0.50903654, 0.932527  ,
       0.08332377, 0.64066132, 0.94727904, 0.0395494 , 0.57230384])

In [35]:
arr = arr.reshape((5,5))

In [36]:
arr

array([[0.14008585, 0.62940221, 0.87672557, 0.41558192, 0.72639928],
       [0.1562309 , 0.69062982, 0.12441599, 0.71362922, 0.33172497],
       [0.46539404, 0.71359483, 0.66458543, 0.20541592, 0.07947435],
       [0.52723854, 0.17489917, 0.71518701, 0.50903654, 0.932527  ],
       [0.08332377, 0.64066132, 0.94727904, 0.0395494 , 0.57230384]])

In [38]:
arr.shape

(5, 5)

In [39]:
arr.max()

0.9472790402259874

In [40]:
arr.min()

0.03954940441698407

In [41]:
arr.argmax()

22

In [42]:
arr.argmin()

23